create table if not exists public.action_review_interest (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_diagnostic text not null check (source_diagnostic in ('readiness_check', 'stress_test', 'direct')),
  diagnostic_score integer check (diagnostic_score between 0 and 100),
  diagnostic_profile text,
  primary_exposure text,
  interest_level text not null check (interest_level in ('yes', 'maybe', 'not_now')),
  price_range text not null check (price_range in ('under_50', '50_99', '100_199', '200_plus', 'unsure')),
  review_focus text,
  valuable_outcome text,
  email text
);

alter table public.action_review_interest enable row level security;

create policy "Allow anonymous action review interest"
on public.action_review_interest
for insert
to anon
with check (
  source_diagnostic in ('readiness_check', 'stress_test', 'direct')
  and interest_level in ('yes', 'maybe', 'not_now')
  and price_range in ('under_50', '50_99', '100_199', '200_plus', 'unsure')
  and (diagnostic_score is null or diagnostic_score between 0 and 100)
);

grant insert on table public.action_review_interest to anon;
grant usage, select on sequence public.action_review_interest_id_seq to anon;

comment on table public.action_review_interest is
'Anonymous commercial validation for the proposed Forge Readiness Action Review. Email is optional.';
