create table if not exists public.pulse_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  role text not null,
  region text not null,
  enrolment numeric not null,
  department_fte numeric not null,
  competitive_teams numeric not null,
  annual_fixtures numeric not null,
  admin_support text not null,
  workload_pressure text not null,
  hardest_recruitment text not null,
  recurring_headache text not null,
  live_decision text not null,
  decision_detail text,
  email text
);

alter table public.pulse_responses enable row level security;

create policy "anonymous pulse submissions"
on public.pulse_responses
for insert
to anon
with check (true);

-- No anonymous SELECT policy: public visitors can contribute data but cannot read the dataset.
