create table if not exists public.readiness_check_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  answers jsonb not null,
  readiness_score integer not null check (readiness_score between 0 and 100),
  profile text not null,
  people_score integer not null check (people_score between 0 and 100),
  programme_score integer not null check (programme_score between 0 and 100),
  operations_score integer not null check (operations_score between 0 and 100),
  safety_score integer not null check (safety_score between 0 and 100),
  communication_score integer not null check (communication_score between 0 and 100),
  capacity_score integer not null check (capacity_score between 0 and 100),
  strongest_area text not null,
  weakest_area text not null
);

alter table public.readiness_check_responses enable row level security;

create policy "Allow anonymous readiness inserts"
on public.readiness_check_responses
for insert
to anon
with check (
  readiness_score between 0 and 100
  and people_score between 0 and 100
  and programme_score between 0 and 100
  and operations_score between 0 and 100
  and safety_score between 0 and 100
  and communication_score between 0 and 100
  and capacity_score between 0 and 100
);

grant insert on table public.readiness_check_responses to anon;
grant usage, select on sequence public.readiness_check_responses_id_seq to anon;

comment on table public.readiness_check_responses is
'Anonymous Forge Sport Year Readiness Check results. No school or respondent identity is collected.';
