create table if not exists public.stress_test_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  desired_next_step text not null,
  biggest_challenge text,
  email text,
  forge_score integer,
  profile text,
  weakest_dimension text,
  weakest_score integer,
  strongest_dimension text,
  strongest_score integer
);

alter table public.stress_test_feedback enable row level security;

create policy "Allow anonymous feedback inserts"
on public.stress_test_feedback
for insert
to anon
with check (true);

comment on table public.stress_test_feedback is
'Post-Stress-Test commercial discovery data. Stores desired next step, current operational challenge, optional email, and diagnostic context for Forge validation.';
