import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Benchmarking | Forge", description: "Forge is building confidential benchmarking for international-school sport departments." };
const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;
const Arrow = () => <span aria-hidden="true">↗</span>;
const future = [["01","Comparable context","Compare departments with relevant peers rather than a meaningless universal average."],["02","System patterns","Understand which operating strengths and vulnerabilities recur across the field."],["03","Progress over time","Use repeated measurement to see whether the department is genuinely becoming more resilient."],["04","Better decisions","Turn comparative intelligence into clearer priorities for leadership attention and investment."]];

export default function BenchmarkingPage() {
  return <main className="forge-light overflow-hidden">
    <header className="border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/stress-test">Stress Test</Link><Link href="/insights">Insights</Link><Link href="/systems">Systems</Link><Link href="/benchmarking" className="text-[var(--forge-bronze)]">Benchmarking</Link><Link href="/about">About</Link></nav><Link href="/stress-test" className="forge-button forge-button-primary">Start the test <Arrow /></Link></div></header>

    <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid min-h-[680px] gap-14 py-20 lg:grid-cols-12 lg:items-end lg:py-28"><div className="lg:col-span-4 lg:self-start"><p className="forge-eyebrow">Forge benchmarking / in development</p></div><div className="lg:col-span-8"><h1 className="forge-display max-w-4xl text-[clamp(4rem,7vw,7.4rem)]">Good compared with what?</h1><p className="mt-10 max-w-3xl text-xl leading-9 text-[rgba(246,244,238,0.7)]">Sports leaders can see their own programme. What is much harder is knowing how the underlying department compares with relevant peers. Forge is beginning to build that picture.</p></div></div></section>

    <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">The opportunity</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">From isolated experience to shared intelligence.</h2><p className="mt-10 max-w-3xl text-lg leading-8 text-[rgba(17,19,17,0.66)]">The long-term aim is confidential, context-aware benchmarking built from real departmental data. Forge is not yet publishing benchmark claims. The current Stress Test is the first instrument for learning what can be measured reliably and usefully.</p></div></div></section>

    <section className="forge-section border-b forge-border pt-0"><div className="forge-container"><div className="grid border-l border-t forge-border md:grid-cols-2">{future.map(([number,title,text]) => <article key={number} className="min-h-[250px] border-b border-r p-8 forge-border lg:p-10"><span className="forge-eyebrow">{number}</span><h2 className="forge-heading mt-12 text-3xl text-[var(--forge-forest-deep)]">{title}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[rgba(17,19,17,0.62)]">{text}</p></article>)}</div></div></section>

    <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Confidential by design</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl md:text-7xl">Learn from departments without turning schools into a league table.</h2><p className="mt-10 max-w-3xl text-lg leading-8 text-[rgba(246,244,238,0.7)]">Forge is interested in aggregated patterns and relevant comparisons, not public rankings. Any future benchmark product must protect participating departments and earn trust before it earns scale.</p></div></div></section>

    <section className="forge-dark forge-section"><div className="forge-container grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Help build the baseline</p><h2 className="forge-heading mt-8 text-5xl md:text-7xl">Measure your department first.</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/stress-test" className="forge-button forge-button-primary">Take the free stress test <Arrow /></Link><p className="mt-5 text-xs uppercase tracking-[0.13em] text-[rgba(246,244,238,0.5)]">Confidential · approximately 10 minutes</p></div></div></section>
  </main>;
}
