import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Benchmarking | Forge",
  description: "Confidential benchmarking for school sports departments and school-sports associations.",
};

const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;

const departmentMetrics = ["Participation rate","Teams and competitive opportunities","Programme breadth","Staffing and coaching capacity","Fixture volume and completion","Operational resilience"];
const associationMetrics = ["Member-school participation","Sports, seasons and teams","Staffing and resources","Fixtures, travel and cancellations","Student experience and pathways","Year-on-year association trends"];

export default function BenchmarkingPage() {
  return (
    <main className="forge-light overflow-hidden">
      <header className="border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/departments">Departments</Link><Link href="/associations">Associations</Link><Link href="/insights">Insights</Link><Link href="/systems">Systems</Link><Link href="/benchmarking" className="text-[var(--forge-bronze)]">Benchmarking</Link><Link href="/about">About</Link></nav><Link href="/diagnostics" className="forge-button forge-button-primary">Start a diagnostic</Link></div></header>

      <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid min-h-[680px] gap-14 py-20 lg:grid-cols-12 lg:items-end lg:py-28"><div className="lg:col-span-4 lg:self-start"><p className="forge-eyebrow">Benchmarking</p></div><div className="lg:col-span-8"><h1 className="forge-display max-w-5xl text-[clamp(4rem,7vw,7.4rem)]">Compare with relevant peers.</h1><p className="mt-10 max-w-3xl text-xl leading-9 text-[rgba(246,244,238,0.7)]">Forge is developing confidential benchmarking for school sports departments and school-sports associations.</p></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Two levels</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Department and association benchmarking.</h2></div></div><div className="forge-container mt-16 grid border-l border-t forge-border md:grid-cols-2"><article className="flex min-h-[520px] flex-col justify-between border-b border-r p-8 forge-border lg:p-10"><div><p className="forge-eyebrow">Department Benchmark</p><h3 className="forge-heading mt-10 text-4xl text-[var(--forge-forest-deep)] md:text-5xl">Your school vs relevant peers.</h3><p className="mt-6 max-w-xl text-base leading-7 text-[rgba(17,19,17,0.64)]">The department track starts with the Forge Stress Test and is intended to develop toward confidential peer comparison across selected operating measures.</p><div className="mt-10 divide-y divide-black/10 border-y border-black/10">{departmentMetrics.map(metric=><div key={metric} className="py-3 text-sm">{metric}</div>)}</div></div><Link href="/stress-test" className="mt-10 w-fit text-xs font-semibold uppercase tracking-[0.13em] text-[var(--forge-bronze)] underline underline-offset-8">Take the Department Stress Test</Link></article><article className="flex min-h-[520px] flex-col justify-between border-b border-r bg-[var(--forge-forest)] p-8 text-[var(--forge-ivory)] forge-border lg:p-10"><div><p className="forge-eyebrow">Association Benchmark</p><h3 className="forge-heading mt-10 text-4xl md:text-5xl">Your school vs association median.</h3><p className="mt-6 max-w-xl text-base leading-7 text-[rgba(246,244,238,0.68)]">Member schools complete a structured annual return. The data is used to produce confidential school reports and an association-level State of School Sport report.</p><div className="mt-10 divide-y divide-white/15 border-y border-white/15">{associationMetrics.map(metric=><div key={metric} className="py-3 text-sm text-white/75">{metric}</div>)}</div></div><Link href="/association-health-check" className="mt-10 w-fit text-xs font-semibold uppercase tracking-[0.13em] text-[var(--forge-bronze)] underline underline-offset-8">Take the Association Health Check</Link></article></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Association output</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">State of School Sport.</h2><p className="mt-10 max-w-3xl text-lg leading-8 text-[rgba(17,19,17,0.66)]">The association report summarises participation, programme breadth, resources, operations and student experience across participating schools.</p><div className="mt-12 grid gap-6 md:grid-cols-3">{[["01","Collect","A focused annual school return using a defined set of metrics."],["02","Benchmark","Confidential comparison against association medians and relevant cohorts."],["03","Interpret","Association-level findings, trends and questions based on the data."]].map(([n,t,d])=><div key={n} className="border-t pt-6 forge-border"><p className="forge-eyebrow">{n}</p><h3 className="forge-heading mt-5 text-2xl">{t}</h3><p className="mt-3 text-sm leading-6 text-black/60">{d}</p></div>)}</div></div></div></section>

      <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Confidentiality</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl md:text-7xl">School-level results remain confidential.</h2><p className="mt-10 max-w-3xl text-lg leading-8 text-[rgba(246,244,238,0.7)]">Association reporting is intended to use aggregated results and relevant peer groups rather than public school rankings.</p></div></div></section>

      <section className="forge-dark forge-section"><div className="forge-container grid gap-12 lg:grid-cols-2"><div><p className="forge-eyebrow">For schools</p><h2 className="forge-heading mt-8 text-4xl md:text-6xl">Start with your department.</h2><Link href="/stress-test" className="forge-button forge-button-primary mt-10">Department Stress Test</Link></div><div><p className="forge-eyebrow">For associations</p><h2 className="forge-heading mt-8 text-4xl md:text-6xl">Start with association health.</h2><Link href="/association-health-check" className="forge-button forge-button-primary mt-10">Association Health Check</Link></div></div></section>
    </main>
  );
}
