import Link from "next/link";

const stats = [["25","Member schools"],["18,420","Students"],["6,280","Competitive athletes"],["412","Teams"],["2,740","Fixtures"],["23","Sports"]];
const findings = [
  ["Participation", "Median competitive participation is 51%, with substantial variation between schools of similar size."],
  ["Opportunity", "Higher-performing programmes tend to concentrate on team depth rather than simply adding more sports."],
  ["Operations", "Fixture completion is generally strong, but travel burden and late changes remain visible pressure points."],
  ["Resources", "Staffing intensity varies widely, creating materially different delivery models across the association."],
  ["Student experience", "Multi-sport participation and athlete retention show more variation than headline participation rates."],
];

export default function StateOfSchoolSportSamplePage() {
  return <main className="min-h-screen bg-[#f3f0e8] text-black">
    <header className="border-b border-black/20"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="text-sm font-semibold tracking-[0.18em]">FORGE</Link><span className="text-right text-[10px] font-semibold tracking-[0.14em] text-black/55 md:text-xs">STATE OF SCHOOL SPORT · SAMPLE</span></div></header>
    <section className="bg-black text-[#f3f0e8]"><div className="mx-auto grid min-h-[72vh] max-w-[1500px] gap-12 px-6 py-16 md:grid-cols-12 md:px-10 md:py-24"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-white/50">FOR ASSOCIATION LEADERSHIP</p></div><div className="md:col-span-8 md:self-end"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/50">Fictional demonstration data</p><h1 className="mt-7 max-w-5xl text-6xl font-semibold uppercase leading-[0.86] tracking-[-0.06em] md:text-8xl">State of School Sport 2027</h1><p className="mt-9 max-w-3xl text-xl leading-9 text-white/65">An annual evidence base showing what is happening across the association, where member schools differ, and which questions deserve leadership attention.</p></div></div></section>
    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] grid-cols-2 md:grid-cols-3 lg:grid-cols-6">{stats.map(([value,label]) => <div key={label} className="border-b border-r border-black/20 px-6 py-9 md:px-8"><p className="text-4xl font-semibold tracking-[-0.05em] md:text-5xl">{value}</p><p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-black/45">{label}</p></div>)}</div></section>
    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-black/50">HEADLINE FINDINGS</p></div><div className="md:col-span-8">{findings.map(([title,text],i) => <div key={title} className="grid gap-4 border-t border-black/20 py-7 md:grid-cols-[48px_180px_1fr]"><span className="text-sm text-black/35">0{i+1}</span><h2 className="text-sm font-semibold uppercase tracking-[0.1em]">{title}</h2><p className="text-lg leading-8 text-black/65">{text}</p></div>)}</div></div></section>
    <section className="border-b border-black/20 bg-[#14372f] text-[#f3f0e8]"><div className="mx-auto grid max-w-[1500px] gap-12 px-6 py-16 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-white/50">WHAT THE ASSOCIATION CAN NOW ASK</p></div><div className="md:col-span-8"><h2 className="max-w-4xl text-4xl font-semibold uppercase leading-[0.95] tracking-[-0.05em] md:text-6xl">Which differences matter enough to act on?</h2><div className="mt-10 space-y-7 text-xl leading-8 text-white/70"><p>Where is participation genuinely strong after controlling for school size?</p><p>Which operating models produce high opportunity without excessive travel or staffing pressure?</p><p>Where should the association standardise, where should it support, and where should it simply learn from member variation?</p></div></div></div></section>
    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-black/50">ANNUAL CYCLE</p></div><div className="md:col-span-8"><div className="grid gap-4 sm:grid-cols-5">{["Collect","Clean","Benchmark","Interpret","Improve"].map((step,i)=><div key={step} className="border border-black/20 p-5"><span className="text-xs text-black/35">0{i+1}</span><p className="mt-8 text-sm font-semibold uppercase tracking-[0.1em]">{step}</p></div>)}</div><p className="mt-8 max-w-2xl text-sm leading-7 text-black/55">The report improves as definitions stabilise, participation increases and multiple years of comparable data accumulate.</p></div></div></section>
    <section className="px-6 py-12 md:px-10"><div className="mx-auto flex max-w-[1500px] flex-wrap gap-6"><Link href="/association-benchmark-return" className="border-b border-black pb-1 text-xs font-semibold uppercase tracking-[0.14em]">Open pilot data return</Link><Link href="/association-benchmark-sample" className="border-b border-black pb-1 text-xs font-semibold uppercase tracking-[0.14em]">View sample school report</Link></div></section>
  </main>;
}
