import Link from "next/link";

const stats = [["25","Member schools"],["18,420","Students"],["6,280","Competitive athletes"],["412","Teams"],["2,740","Fixtures"],["23","Sports"]];
const findings = [
  ["Participation", "Median competitive participation is 51%, with substantial variation between schools of similar size."],
  ["Opportunity", "Higher-opportunity programmes appear to build greater team depth rather than simply adding more sports."],
  ["Operations", "Fixture completion is generally strong, while travel burden and late changes remain visible pressure points."],
  ["Resources", "Staffing intensity varies widely, creating materially different delivery models across the association."],
  ["Student experience", "Multi-sport participation and athlete retention vary more than headline participation rates."],
];
const distributions = [
  ["Competitive participation", "51%", "34–67%", 51],
  ["Fixture completion", "89%", "76–97%", 89],
  ["Multi-sport participation", "42%", "21–58%", 42],
  ["Athlete retention", "78%", "63–91%", 78],
];
const pressures = [
  ["01","Travel burden","8 schools",68],
  ["02","Staffing capacity","7 schools",59],
  ["03","Fixture volatility","5 schools",43],
  ["04","Data consistency","11 schools",82],
];
const questions = [
  "Where is participation genuinely strong after controlling for school size and programme context?",
  "Which operating models create high competitive opportunity without excessive staffing or travel pressure?",
  "Why do comparable schools show materially different multi-sport participation and athlete retention?",
  "Which measures should the association standardise so year-on-year comparisons become more reliable?",
  "Where should the association intervene, where should it facilitate peer learning, and where is variation healthy?",
];

export default function StateOfSchoolSportSamplePage() {
  return <main className="min-h-screen bg-[#f3f0e8] text-black overflow-hidden">
    <header className="border-b border-black/20"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="text-sm font-semibold tracking-[0.18em]">FORGE</Link><span className="text-right text-[10px] font-semibold tracking-[0.14em] text-black/55 md:text-xs">STATE OF SCHOOL SPORT · PROTOTYPE</span></div></header>

    <section className="bg-[#081a16] text-[#f3f0e8]"><div className="mx-auto grid min-h-[76vh] max-w-[1500px] gap-12 px-6 py-16 md:grid-cols-12 md:px-10 md:py-24"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">FOR ASSOCIATION LEADERSHIP</p><p className="mt-5 max-w-xs text-sm leading-6 text-white/45">Prototype annual intelligence report<br/>Illustrative cohort only</p></div><div className="md:col-span-8 md:self-end"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/45">Fictional demonstration data · not a real benchmark</p><h1 className="mt-7 max-w-5xl font-serif text-6xl leading-[0.88] tracking-[-0.055em] md:text-8xl">State of School Sport 2027</h1><p className="mt-9 max-w-3xl text-xl leading-9 text-white/65">An annual evidence base showing what is happening across the association, how member schools differ, and which questions deserve leadership attention.</p><div className="mt-10 flex flex-wrap gap-7"><Link href="/association-pilot" className="text-xs font-semibold uppercase tracking-[0.14em] text-[#b9864a] underline underline-offset-8">Explore a pilot</Link><Link href="/association-benchmark-return" className="text-xs font-semibold uppercase tracking-[0.14em] text-white/70 underline underline-offset-8">View the data return</Link></div></div></div></section>

    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] grid-cols-2 md:grid-cols-3 lg:grid-cols-6">{stats.map(([value,label]) => <div key={label} className="border-b border-r border-black/20 px-6 py-9 md:px-8"><p className="font-serif text-4xl tracking-[-0.04em] text-[#102c24] md:text-5xl">{value}</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-black/45">{label}</p></div>)}</div></section>

    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">EXECUTIVE SIGNAL</p><h2 className="mt-7 max-w-sm font-serif text-4xl leading-[1.02] text-[#102c24] md:text-5xl">Variation is the starting point, not the verdict.</h2></div><div className="md:col-span-8"><p className="max-w-3xl text-xl leading-9 text-black/65">The association-wide average hides materially different programme models. The useful question is not which school ranks first. It is which differences are meaningful after context, and what the network can learn from them.</p><div className="mt-10 border-l-2 border-[#b9864a] pl-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-black/40">Illustrative leadership priority</p><p className="mt-3 max-w-2xl text-lg leading-8">Improve data consistency first. Eleven of 25 fictional member schools would currently require clarification before several metrics could support reliable peer comparison.</p></div></div></div></section>

    <section className="border-b border-black/20 bg-white/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">NETWORK DISTRIBUTION</p><p className="mt-5 max-w-xs text-sm leading-6 text-black/50">Median and illustrative middle-range context. No public school ranking.</p></div><div className="md:col-span-8 space-y-8">{distributions.map(([label,median,range,width]) => <div key={label as string}><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-[0.1em]">{label}</p><p className="mt-1 text-xs text-black/40">Illustrative middle range {range}</p></div><div className="text-right"><span className="font-serif text-3xl text-[#102c24]">{median}</span><span className="ml-2 text-xs uppercase tracking-[0.1em] text-black/35">median</span></div></div><div className="h-3 bg-black/10"><div className="h-full bg-[#102c24]" style={{width:`${width}%`}} /></div></div>)}</div></div></section>

    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">HEADLINE FINDINGS</p></div><div className="md:col-span-8">{findings.map(([title,text],i) => <div key={title} className="border-t border-black/20 py-7 md:grid md:grid-cols-[48px_180px_1fr] md:gap-4"><div className="flex items-baseline gap-5 md:contents"><span className="text-sm text-[#b9864a]">0{i+1}</span><h2 className="text-sm font-semibold uppercase tracking-[0.1em]">{title}</h2></div><p className="mt-4 text-lg leading-8 text-black/65 md:mt-0">{text}</p></div>)}</div></div></section>

    <section className="border-b border-black/20 bg-[#102c24] text-[#f3f0e8]"><div className="mx-auto grid max-w-[1500px] gap-12 px-6 py-16 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">OPERATIONAL PRESSURE</p><h2 className="mt-7 max-w-sm font-serif text-4xl leading-[1.02] md:text-5xl">Where the network feels strain.</h2></div><div className="md:col-span-8">{pressures.map(([number,label,value,width]) => <div key={label as string} className="border-t border-white/15 py-6"><div className="flex items-center gap-4"><span className="text-xs text-[#b9864a]">{number}</span><p className="flex-1 text-sm font-semibold uppercase tracking-[0.1em]">{label}</p><strong className="text-sm text-white/70">{value}</strong></div><div className="mt-4 h-2 bg-white/10"><div className="h-full bg-[#b9864a]" style={{width:`${width}%`}} /></div></div>)}</div></div></section>

    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">FIVE QUESTIONS FOR LEADERSHIP</p></div><div className="md:col-span-8">{questions.map((question,i) => <div key={question} className="grid grid-cols-[38px_1fr] gap-3 border-t border-black/20 py-6 md:grid-cols-[55px_1fr]"><span className="text-sm text-[#b9864a]">0{i+1}</span><p className="font-serif text-2xl leading-8 text-[#102c24] md:text-3xl md:leading-10">{question}</p></div>)}</div></div></section>

    <section className="border-b border-black/20 bg-[#081a16] text-[#f3f0e8]"><div className="mx-auto grid max-w-[1500px] gap-12 px-6 py-16 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">WHAT CHANGES IN YEAR TWO</p></div><div className="md:col-span-8"><h2 className="max-w-4xl font-serif text-4xl leading-[1.02] md:text-6xl">The benchmark becomes more valuable after every cycle.</h2><div className="mt-10 grid gap-px bg-white/15 sm:grid-cols-3"><div className="bg-[#081a16] p-6"><p className="text-xs uppercase tracking-[0.12em] text-white/35">Year 01</p><p className="mt-5 text-lg">Establish definitions and the association baseline.</p></div><div className="bg-[#081a16] p-6"><p className="text-xs uppercase tracking-[0.12em] text-white/35">Year 02</p><p className="mt-5 text-lg">Measure movement and identify persistent differences.</p></div><div className="bg-[#081a16] p-6"><p className="text-xs uppercase tracking-[0.12em] text-white/35">Year 03+</p><p className="mt-5 text-lg">Build longitudinal evidence that individual schools cannot create alone.</p></div></div></div></div></section>

    <section className="border-b border-black/20"><div className="mx-auto grid max-w-[1500px] gap-10 px-6 py-14 md:grid-cols-12 md:px-10 md:py-20"><div className="md:col-span-4"><p className="text-xs font-semibold tracking-[0.18em] text-[#b9864a]">ANNUAL CYCLE</p></div><div className="md:col-span-8"><div className="grid gap-3 sm:grid-cols-5">{["Collect","Validate","Benchmark","Interpret","Improve"].map((step,i)=><div key={step} className="border border-black/20 p-5"><span className="text-xs text-[#b9864a]">0{i+1}</span><p className="mt-8 text-sm font-semibold uppercase tracking-[0.1em]">{step}</p></div>)}</div><p className="mt-8 max-w-2xl text-sm leading-7 text-black/55">The report improves as definitions stabilise, participation increases and multiple years of comparable data accumulate.</p></div></div></section>

    <section className="bg-[#b9864a] px-6 py-14 text-[#081a16] md:px-10"><div className="mx-auto grid max-w-[1500px] gap-8 md:grid-cols-12 md:items-end"><div className="md:col-span-8"><p className="text-xs font-semibold uppercase tracking-[0.16em]">Pilot proposition</p><h2 className="mt-6 max-w-4xl font-serif text-4xl leading-[1.02] md:text-6xl">Would this be useful enough to run annually across your member schools?</h2></div><div className="md:col-span-4 md:text-right"><Link href="/association-pilot" className="text-xs font-semibold uppercase tracking-[0.14em] underline underline-offset-8">Register pilot interest</Link></div></div></section>
  </main>;
}
