import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Forge",
  description: "Forge is an independent research project examining the systems behind sports leadership in international schools.",
};

const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;
const systems = ["Leadership and direction","People and accountability","Systems and operations","Opportunities and pathways","Evidence and improvement","Resilience and continuity"];

export default function AboutPage() {
  return (
    <main className="forge-light overflow-hidden">
      <header className="relative z-20 border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Forge home"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-9 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/stress-test">Research</Link><Link href="/insights">Insights</Link><Link href="/about" aria-current="page" className="text-[var(--forge-bronze)]">About</Link></nav><Link href="/stress-test?source=about&campaign=research_project" className="forge-button forge-button-primary">Take part</Link></div></header>

      <section className="border-b forge-border"><div className="forge-container grid min-h-[680px] lg:grid-cols-12"><div className="flex flex-col justify-between py-20 lg:col-span-8 lg:border-r lg:pr-16 forge-border xl:py-28"><div><div className="mb-12 flex items-center gap-4"><span className="forge-rule" /><p className="forge-eyebrow">About Forge</p></div><h1 className="forge-display max-w-4xl text-[clamp(4rem,7vw,7.5rem)] text-[var(--forge-forest-deep)]">Independent research into the systems behind school sport.</h1></div><p className="mt-16 max-w-3xl border-t pt-8 text-xl leading-9 text-[rgba(17,19,17,0.7)] forge-border md:text-2xl">Forge explores how sports departments in international schools operate, where operational fragility appears, and what stronger systems may look like in practice.</p></div><aside className="flex flex-col justify-between py-20 lg:col-span-4 lg:pl-12 xl:py-28 xl:pl-16"><div className="relative mx-auto aspect-square w-full max-w-[290px]"><div className="absolute inset-0 rotate-45 border border-[rgba(185,134,74,0.4)]" /><div className="absolute inset-[18%] rotate-45 bg-[var(--forge-forest)]" /><ForgeMark className="absolute inset-[36%] h-[28%] w-[28%] object-contain" /></div><div className="mt-16 border-t pt-6 forge-border"><p className="forge-eyebrow">Current focus</p><p className="mt-3 text-sm leading-6 text-[rgba(17,19,17,0.58)]">Operational resilience in international-school sports departments.</p></div></aside></div></section>

      <section className="forge-dark forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Why Forge exists</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl md:text-7xl">Strong outcomes can hide fragile operations.</h2><div className="mt-12 grid gap-8 border-t border-[rgba(185,134,74,0.35)] pt-8 md:grid-cols-2"><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">School sport depends on people, calendars, communication, coaching, facilities and repeated operational processes. Much of that work is difficult to see from outcomes alone.</p><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">Forge uses structured diagnostics and research to examine those systems and build a useful evidence base over time.</p></div></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">What Forge examines</p><p className="mt-6 max-w-sm text-base leading-7 text-[rgba(17,19,17,0.62)]">Six areas currently form the first research instrument.</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-3xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">The operating system behind the programme.</h2><div className="mt-12 grid border-l border-t forge-border md:grid-cols-2">{systems.map((item,index)=><div key={item} className="min-h-[150px] border-b border-r p-7 forge-border"><span className="forge-eyebrow">{String(index+1).padStart(2,"0")}</span><p className="forge-heading mt-8 text-2xl">{item}</p></div>)}</div></div></div></section>

      <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">How the work develops</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-3xl text-5xl md:text-7xl">Research. Patterns. Practical knowledge.</h2><div className="mt-14 border-t border-[rgba(185,134,74,0.35)]"><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_180px_1fr]"><span className="forge-eyebrow">01</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Collect</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">Gather structured perspectives on how sports operations actually work.</p></div><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_180px_1fr]"><span className="forge-eyebrow">02</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Examine</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">Look for recurring weaknesses, strengths, questions and potentially useful patterns.</p></div><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_180px_1fr]"><span className="forge-eyebrow">03</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Share</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">Turn credible findings into practical research, frameworks and tools for the field.</p></div></div></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Independence & confidentiality</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-3xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Independent. Confidential. Evidence-led.</h2><div className="mt-10 max-w-3xl space-y-6 text-lg leading-8 text-[rgba(17,19,17,0.68)]"><p>Forge is an independent project and is not presented as the research or official position of any school, employer or sports association.</p><p>Diagnostic responses are treated as confidential. Published work will use aggregated or anonymous patterns rather than identifiable school-level results.</p><p>Forge will not present early responses as established benchmarks. Comparisons or broader conclusions will only be made when the available evidence is sufficiently consistent and useful.</p></div></div></div></section>

      <section className="forge-dark forge-section"><div className="forge-container grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Current study</p><h2 className="forge-heading mt-8 max-w-4xl text-5xl md:text-7xl">How resilient is your sports operation?</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/stress-test?source=about&campaign=research_project" className="forge-button forge-button-primary">Take the Stress Test</Link></div></div></section>
    </main>
  );
}
