import Link from "next/link";

const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;

const researchAreas = [
  ["01", "Leadership & direction", "How clearly priorities, authority and strategic choices are understood."],
  ["02", "People & accountability", "How ownership, expectations and productive challenge work in practice."],
  ["03", "Systems & operations", "How reliably recurring work can be delivered without depending on memory."],
  ["04", "Opportunities & pathways", "How sporting opportunities are designed, explained and reviewed."],
  ["05", "Evidence & improvement", "How departments learn whether changes and programmes are actually working."],
  ["06", "Resilience & continuity", "How well operations survive absence, turnover and leadership change."],
];

export default function Home() {
  return (
    <main className="forge-light overflow-hidden">
      <header className="relative z-20 border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Forge home"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/stress-test">Research</Link><Link href="/insights">Insights</Link><Link href="/about">About</Link></nav><Link href="/stress-test?source=website&campaign=research_project" className="forge-button forge-button-primary">Take part</Link></div></header>

      <section className="relative border-b forge-border"><div className="forge-container grid min-h-[calc(100vh-76px)] items-stretch lg:grid-cols-[minmax(0,1fr)_360px] xl:grid-cols-[minmax(0,1fr)_430px]"><div className="flex flex-col justify-between py-16 lg:py-20 xl:py-24"><div><div className="mb-12 flex items-center gap-4"><span className="forge-rule" /><p className="forge-eyebrow">Independent research · International school sport</p></div><h1 className="forge-display max-w-[980px] text-[clamp(4rem,7.8vw,8rem)] text-[var(--forge-forest-deep)]">How resilient are school sports departments?</h1></div><div className="mt-16 grid max-w-[940px] gap-8 border-t pt-8 forge-border md:grid-cols-[1fr_auto] md:items-end"><div><p className="max-w-2xl text-lg leading-8 text-[rgba(17,19,17,0.72)] xl:text-xl">Forge is an independent research project exploring how sports departments in international schools operate, where operational fragility appears, and which systems support stronger, more resilient programmes.</p><p className="mt-4 max-w-2xl text-sm leading-6 text-[rgba(17,19,17,0.55)]">Study 01 is a confidential Systems Stress Test. No name or school is required to complete it. Participants receive an immediate individual result, while responses contribute to an anonymous evidence base.</p></div><div className="flex flex-col items-start gap-3 md:items-end"><Link href="/stress-test?source=website&campaign=research_project" className="forge-button forge-button-primary w-fit">Take part in Study 01</Link><span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[rgba(17,19,17,0.45)]">30 questions · about 10 minutes</span></div></div></div><aside className="relative hidden border-l forge-border lg:flex lg:flex-col lg:justify-between lg:py-20 lg:pl-12 xl:py-24 xl:pl-16"><div className="relative aspect-square w-full max-w-[330px]"><div className="absolute inset-0 rotate-45 border border-[rgba(185,134,74,0.4)]" /><div className="absolute inset-[15%] rotate-45 border border-[rgba(185,134,74,0.28)]" /><div className="absolute inset-[30%] rotate-45 bg-[var(--forge-forest)]" /><ForgeMark className="absolute inset-[36%] h-[28%] w-[28%] object-contain" /></div><div className="border-t pt-6 forge-border"><p className="forge-eyebrow">Research question 01</p><p className="mt-3 max-w-[290px] text-sm leading-6 text-[rgba(17,19,17,0.58)]">Where do international-school sports operations depend most heavily on individuals, informal knowledge and fragile systems?</p></div></aside></div></section>

      <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 py-20 lg:grid-cols-12 lg:py-28"><div className="lg:col-span-4"><p className="forge-eyebrow">The research</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-4xl md:text-6xl">School sport is highly visible. The systems behind it are not.</h2><div className="mt-12 grid gap-8 border-t border-[rgba(185,134,74,0.35)] pt-8 md:grid-cols-2"><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">Departments can deliver full calendars, competitions and strong experiences while still relying heavily on individual knowledge, unclear ownership or processes rebuilt each year.</p><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">Forge is collecting structured, confidential responses to identify recurring patterns and develop a more useful evidence base for sports leaders.</p></div></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Study 01 · Systems Stress Test</p><p className="mt-6 max-w-sm text-sm leading-6 text-[rgba(17,19,17,0.6)]">30 questions · 6 areas · Approx. 10 minutes · Confidential</p></div><div className="lg:col-span-8"><h2 className="forge-heading text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Contribute your department&apos;s perspective.</h2><p className="mt-8 max-w-3xl text-xl leading-8 text-[rgba(17,19,17,0.68)]">Answer based on how your sports operation actually works today. You will receive a Forge Score, six system scores, your strongest area, primary vulnerability, fragility signals and one priority action.</p><Link href="/stress-test?source=website&campaign=research_project" className="forge-button forge-button-primary mt-8">Take part in the research</Link></div></div><div className="mt-16 grid border-l border-t forge-border md:grid-cols-2 lg:grid-cols-3">{researchAreas.map(([number,title,description])=><article key={number} className="min-h-[245px] border-b border-r p-7 forge-border lg:p-9"><div className="flex items-center justify-between"><span className="forge-eyebrow">{number}</span><span className="h-2 w-2 rotate-45 bg-[var(--forge-bronze)]" /></div><h3 className="forge-heading mt-14 text-2xl">{title}</h3><p className="mt-4 text-sm leading-6 text-[rgba(17,19,17,0.6)]">{description}</p></article>)}</div></div></section>

      <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">What happens to the data?</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl md:text-7xl">Individual insight. Collective learning.</h2><div className="mt-14 border-t border-[rgba(185,134,74,0.35)]"><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_190px_1fr]"><span className="forge-eyebrow">01</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Participate</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">Complete the confidential diagnostic and receive an immediate result.</p></div><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_190px_1fr]"><span className="forge-eyebrow">02</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Aggregate</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">Responses are examined as anonymous patterns rather than identifiable school-level results.</p></div><div className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_190px_1fr]"><span className="forge-eyebrow">03</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">Learn</h3><p className="text-lg text-[rgba(246,244,238,0.68)]">As the evidence base develops, Forge will publish emerging patterns, practical findings and research questions.</p></div></div></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Research standard</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">No invented benchmarks. No false certainty.</h2><div className="mt-10 max-w-3xl space-y-6 text-lg leading-8 text-[rgba(17,19,17,0.68)]"><p>Forge will distinguish between individual diagnostic results, early patterns and findings supported by a sufficiently useful body of comparable responses.</p><p>Where the evidence is too limited to support a conclusion or comparison, that limitation will be stated plainly.</p></div></div></div></section>

      <section className="forge-dark forge-section"><div className="forge-container grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Contribute</p><h2 className="forge-heading mt-8 max-w-4xl text-5xl md:text-7xl">Add your experience to the research.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[rgba(246,244,238,0.66)]">The value of the research improves as more sports leaders contribute honest perspectives on how their departments actually operate.</p></div><div className="lg:col-span-4 lg:text-right"><Link href="/stress-test?source=website&campaign=research_project" className="forge-button forge-button-primary">Take the Stress Test</Link></div></div></section>
    </main>
  );
}
