import Link from "next/link";

const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;

const dimensions = [
  ["01", "Leadership dependency", "How much does the operation depend on one person?"],
  ["02", "Operational clarity", "Are routines, responsibilities and standards clear?"],
  ["03", "Ownership", "Are important responsibilities clearly owned?"],
  ["04", "Coaching consistency", "Are expectations consistent across teams and coaches?"],
  ["05", "Knowledge resilience", "Is important operational knowledge recorded and accessible?"],
  ["06", "Capacity to improve", "Is there enough capacity to improve while delivering the programme?"],
];

const method = [
  ["01", "Measure", "Establish what is happening now."],
  ["02", "Understand", "Identify the main constraint or weakness."],
  ["03", "Improve", "Take a practical next step and review the result."],
];

const ecosystem = [
  ["01", "Diagnostics", "Structured checks for school sports departments and sports associations.", "/diagnostics", "Choose a diagnostic"],
  ["02", "Insights", "Short research and observations on recurring sports-leadership problems.", "/insights", "Explore insights"],
  ["03", "Systems", "Practical frameworks and protocols for recurring operational problems.", "/systems", "Explore systems"],
  ["04", "Benchmarking", "A developing evidence base for confidential comparison with relevant peers.", "/benchmarking", "Explore benchmarking"],
];

export default function Home() {
  return (
    <main className="forge-light overflow-hidden">
      <header className="relative z-20 border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Forge home"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/diagnostics">Diagnostics</Link><Link href="/departments">Departments</Link><Link href="/associations">Associations</Link><Link href="/insights">Insights</Link><Link href="/systems">Systems</Link><Link href="/benchmarking">Benchmarking</Link><Link href="/about">About</Link></nav><Link href="/diagnostics" className="forge-button forge-button-primary">Start a diagnostic</Link></div></header>

      <section className="relative border-b forge-border"><div className="forge-container grid min-h-[calc(100vh-76px)] items-stretch lg:grid-cols-[minmax(0,1fr)_360px] xl:grid-cols-[minmax(0,1fr)_430px]"><div className="flex flex-col justify-between py-16 lg:py-20 xl:py-24"><div><div className="mb-12 flex items-center gap-4"><span className="forge-rule" /><p className="forge-eyebrow">Research and diagnostics for school sports leadership</p></div><h1 className="forge-display max-w-[920px] text-[clamp(4.2rem,8.1vw,8.2rem)] text-[var(--forge-forest-deep)]">Better sport is built on better systems.</h1></div><div className="mt-16 grid max-w-[920px] gap-8 border-t pt-8 forge-border md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-xl text-lg leading-8 text-[rgba(17,19,17,0.72)] xl:text-xl">Forge develops practical diagnostics, research and benchmarking for sports leaders in international schools and school-sports associations.</p><Link href="/diagnostics" className="forge-button forge-button-primary w-fit">Explore diagnostics</Link></div></div><aside className="relative hidden border-l forge-border lg:flex lg:flex-col lg:justify-between lg:py-20 lg:pl-12 xl:py-24 xl:pl-16"><div className="relative aspect-square w-full max-w-[330px]"><div className="absolute inset-0 rotate-45 border border-[rgba(185,134,74,0.4)]" /><div className="absolute inset-[15%] rotate-45 border border-[rgba(185,134,74,0.28)]" /><div className="absolute inset-[30%] rotate-45 bg-[var(--forge-forest)]" /><ForgeMark className="absolute inset-[36%] h-[28%] w-[28%] object-contain" /><span className="absolute left-0 top-1/2 h-px w-full bg-[rgba(185,134,74,0.25)]" /><span className="absolute left-1/2 top-0 h-full w-px bg-[rgba(185,134,74,0.25)]" /></div><div className="border-t pt-6 forge-border"><p className="forge-eyebrow">Measure · Understand · Improve</p><p className="mt-3 max-w-[280px] text-sm leading-6 text-[rgba(17,19,17,0.58)]">A simple approach to examining operational problems and tracking improvement.</p></div></aside></div></section>

      <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 py-20 lg:grid-cols-12 lg:py-28"><div className="lg:col-span-4"><p className="forge-eyebrow">Why systems matter</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-4xl md:text-6xl">Strong delivery depends on more than a full calendar.</h2><div className="mt-12 grid gap-8 border-t border-[rgba(185,134,74,0.35)] pt-8 md:grid-cols-2"><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">School sport relies on clear roles, repeatable processes, good communication and accessible information.</p><p className="text-lg leading-8 text-[rgba(246,244,238,0.72)]">When those systems are weak, workload, continuity and consistency become harder to manage.</p></div></div></div></section>

      <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid lg:grid-cols-12"><figure className="relative min-h-[430px] overflow-hidden lg:col-span-8 lg:min-h-[620px]"><img src="/forge-track.jpg" alt="Empty athletics track and stadium at first light" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[rgba(8,26,22,0.78)] via-transparent to-transparent" /><figcaption className="absolute bottom-8 left-8 forge-eyebrow text-[var(--forge-ivory)] md:bottom-10 md:left-10">School sport operations</figcaption></figure><div className="flex flex-col justify-between border-t border-[rgba(185,134,74,0.35)] px-8 py-10 lg:col-span-4 lg:border-l lg:border-t-0 lg:p-12"><p className="forge-eyebrow">Focus</p><p className="forge-heading mt-24 text-3xl lg:text-4xl">Look at the systems that support delivery, not only the outcomes.</p></div></div></section>

      <section id="diagnostic" className="forge-section border-b forge-border"><div className="forge-container"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Forge diagnostics</p><p className="mt-6 max-w-sm text-sm leading-6 text-[rgba(17,19,17,0.6)]">Choose a diagnostic for a department or association.</p></div><div className="lg:col-span-8"><h2 className="forge-heading text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Start with a structured view of the problem.</h2><p className="mt-8 max-w-2xl text-xl leading-8 text-[rgba(17,19,17,0.68)]">The Systems Stress Test looks at department structure. The Readiness Check focuses on immediate operational preparation. The Association Health Check focuses on association-level operations.</p><Link href="/diagnostics" className="forge-button mt-8 text-[var(--forge-forest-deep)]">See all diagnostics</Link></div></div><div className="mt-16 grid border-l border-t forge-border md:grid-cols-2"><article className="flex min-h-[360px] flex-col justify-between border-b border-r p-8 forge-border lg:p-10"><div><p className="forge-eyebrow">Department · Approx. 10 minutes</p><h3 className="forge-heading mt-10 text-4xl text-[var(--forge-forest-deep)] md:text-5xl">School Sports Systems Stress Test</h3><p className="mt-6 max-w-xl text-base leading-7 text-[rgba(17,19,17,0.64)]">Assess leadership, ownership, operations, knowledge continuity and capacity to improve.</p></div><Link href="/stress-test" className="forge-button forge-button-primary mt-10 w-fit">Start the Stress Test</Link></article><article className="flex min-h-[360px] flex-col justify-between border-b border-r bg-[var(--forge-forest)] p-8 text-[var(--forge-ivory)] forge-border lg:p-10"><div><p className="forge-eyebrow">Department · Approx. 5 minutes</p><h3 className="forge-heading mt-10 text-4xl md:text-5xl">School Sports Readiness Check</h3><p className="mt-6 max-w-xl text-base leading-7 text-[rgba(246,244,238,0.68)]">Identify operational gaps that could disrupt the start of a year or season.</p></div><Link href="/readiness-check" className="forge-button mt-10 w-fit">Start the Readiness Check</Link></article></div>

        <div className="mt-20 grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Systems Stress Test</p><p className="mt-6 max-w-sm text-sm leading-6 text-[rgba(17,19,17,0.6)]">6 areas · Confidential · Immediate result</p></div><div className="lg:col-span-8"><h2 className="forge-heading text-4xl text-[var(--forge-forest-deep)] md:text-6xl">Six areas of operational strength.</h2></div></div><div className="mt-16 grid border-l border-t forge-border md:grid-cols-2 lg:grid-cols-3">{dimensions.map(([number,title,description])=><article key={number} className="group min-h-[250px] border-b border-r p-7 forge-border transition-colors hover:bg-[var(--forge-forest)] hover:text-[var(--forge-ivory)] lg:p-9"><div className="flex items-center justify-between"><span className="forge-eyebrow">{number}</span><span className="h-2 w-2 rotate-45 bg-[var(--forge-bronze)]" /></div><h3 className="forge-heading mt-14 text-2xl">{title}</h3><p className="mt-4 text-sm leading-6 text-[rgba(17,19,17,0.6)] group-hover:text-[rgba(246,244,238,0.68)]">{description}</p></article>)}</div></div></section>

      <section id="method" className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Method</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-3xl text-5xl md:text-7xl">Measure. Understand. Improve.</h2><div className="mt-16 border-t border-[rgba(185,134,74,0.35)]">{method.map(([number,title,text])=><div key={number} className="grid gap-4 border-b border-[rgba(185,134,74,0.35)] py-7 md:grid-cols-[64px_180px_1fr] md:items-center"><span className="forge-eyebrow">{number}</span><h3 className="text-xs font-semibold uppercase tracking-[0.15em]">{title}</h3><p className="text-base text-[rgba(246,244,238,0.66)] md:text-lg">{text}</p></div>)}</div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Forge research</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Diagnostics, research, systems and benchmarking.</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-[rgba(17,19,17,0.66)]">The work is developing through practical use, diagnostic responses and association research.</p></div></div><div className="mt-16 grid border-l border-t forge-border md:grid-cols-2">{ecosystem.map(([number,title,text,href,cta])=><article key={number} className="flex min-h-[310px] flex-col justify-between border-b border-r p-8 forge-border lg:p-10"><div><span className="forge-eyebrow">{number}</span><h3 className="forge-heading mt-12 text-4xl text-[var(--forge-forest-deep)]">{title}</h3><p className="mt-5 max-w-lg text-sm leading-7 text-[rgba(17,19,17,0.62)]">{text}</p></div><Link href={href} className="mt-10 w-fit text-xs font-semibold uppercase tracking-[0.13em] text-[var(--forge-bronze)] underline underline-offset-8">{cta}</Link></article>)}</div></div></section>

      <section className="forge-dark forge-section"><div className="forge-container grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Start here</p><h2 className="forge-heading mt-8 max-w-4xl text-5xl md:text-7xl">Choose a diagnostic.</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/diagnostics" className="forge-button forge-button-primary">View diagnostics</Link></div></div></section>
    </main>
  );
}
