"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { supabase } from "../../../lib/supabaseClient";

const roles=["Head / Director of Sport","PE / Sport Leader","Sports Administrator","Coach / Teacher","Activities / Athletics Director","Other"];
const volumes=["1–10","11–25","26–50","51–100","100+"];
const tools=["Spreadsheet","School MIS / SIS","Dedicated sports platform","Google / Microsoft Forms","Email","WhatsApp / WeChat / Teams","Calendar","Paper / manual processes","Other"];
const frictions=["Scheduling / opponent coordination","Squad selection","Student availability","Parent consent","Parent communication","Transport","Medical / safeguarding information","Staff allocation","Venue / facility coordination","Chasing responses","Last-minute changes","Results / reporting"];
const breakdowns=["Information in different places","Parents / students responding late","Re-entering the same information","Last-minute changes","Staff coordination","Transport / logistics","Consent / safeguarding","System limitations","Nothing significant","Other"];
const intents=["We'd probably stick with what we have","Interesting, but unlikely to pay","I'd want to investigate it","I'd consider a paid trial","I'd have budget for the right solution","I'd actively want to pilot it"];
type Answers={role:string;fixture_volume:string;current_tools:string[];top_friction:string[];biggest_headache:string;admin_hours:string;breakdown_point:string;satisfaction:number|null;desired_outcome:string;commercial_intent:string;email:string};
const initial:Answers={role:"",fixture_volume:"",current_tools:[],top_friction:[],biggest_headache:"",admin_hours:"",breakdown_point:"",satisfaction:null,desired_outcome:"",commercial_intent:"",email:""};

export default function FixtureFriction(){
 const [started,setStarted]=useState(false),[step,setStep]=useState(0),[a,setA]=useState<Answers>(initial),[done,setDone]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const sections=["CONTEXT","CURRENT WORKFLOW","FRICTION","COST","BREAKDOWN","OUTCOME","COMMERCIAL SIGNAL"];
 const valid=useMemo(()=>[
  !!a.role&&!!a.fixture_volume,
  a.current_tools.length>0,
  a.top_friction.length>0&&a.top_friction.length<=3&&!!a.biggest_headache.trim(),
  !!a.admin_hours,
  !!a.breakdown_point&&a.satisfaction!==null,
  !!a.desired_outcome.trim(),
  !!a.commercial_intent
 ][step],[a,step]);
 const toggle=(key:"current_tools"|"top_friction",v:string,max=99)=>setA(p=>{const arr=p[key]; if(arr.includes(v))return {...p,[key]:arr.filter(x=>x!==v)}; if(arr.length>=max)return p; return {...p,[key]:[...arr,v]};});
 async function submit(){setSaving(true);setError("");const payload={role:a.role,fixture_volume:a.fixture_volume,current_tools:a.current_tools,top_friction:a.top_friction,biggest_headache:a.biggest_headache.trim(),admin_hours:a.admin_hours,breakdown_point:a.breakdown_point,satisfaction:a.satisfaction,desired_outcome:a.desired_outcome.trim(),commercial_intent:a.commercial_intent,email:a.email.trim()||null};const {error}=await supabase.from("fixture_friction_responses").insert([payload]);setSaving(false);if(error){console.error(error);setError("We couldn't save your response. Please try once more.");return}setDone(true);window.scrollTo({top:0,behavior:"smooth"})}
 const Option=({label,selected,onClick}:{label:string;selected:boolean;onClick:()=>void})=><button type="button" onClick={onClick} className={`border px-5 py-4 text-left text-sm font-semibold uppercase tracking-[0.06em] transition ${selected?"border-black bg-black text-white":"border-black/25 hover:border-black"}`}>{label}</button>;
 if(!started)return <main className="min-h-screen bg-[#f3f0e8] text-black"><header className="border-b border-black/20"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="text-sm font-semibold tracking-[0.18em]">FORGE</Link><span className="text-xs font-semibold tracking-[0.16em] text-black/55">RESEARCH #02</span></div></header><section className="border-b border-black/20"><div className="mx-auto grid min-h-[78vh] max-w-[1500px] md:grid-cols-12"><div className="flex flex-col justify-between border-b border-black/20 px-6 py-12 md:col-span-8 md:border-b-0 md:border-r md:px-10 md:py-16"><div><p className="mb-8 text-xs font-semibold tracking-[0.18em]">3 MINUTES · ANONYMOUS · SCHOOL SPORT</p><h1 className="max-w-[1050px] text-[14vw] font-semibold uppercase leading-[0.8] tracking-[-0.07em] md:text-[6.5vw]">Where do<br/>fixtures steal<br/>your time?</h1></div><div className="mt-16 max-w-2xl"><p className="text-xl leading-relaxed md:text-2xl">FORGE is mapping the hidden workload between agreeing a fixture and getting students successfully to competition.</p><p className="mt-6 text-base leading-relaxed text-black/65 md:text-lg">This research is designed to find the real friction before assuming software is the answer.</p><button onClick={()=>setStarted(true)} className="mt-10 bg-black px-7 py-4 text-xs font-semibold tracking-[0.16em] text-white">START RESEARCH #02</button></div></div><aside className="px-6 py-12 md:col-span-4 md:px-10 md:py-16"><p className="text-xs font-semibold tracking-[0.18em] text-black/55">WE'RE INVESTIGATING</p><div className="mt-10 divide-y divide-black/20 border-y border-black/20">{["Where admin time goes","Which tools schools rely on","Where workflows break","The one headache leaders would remove","Whether the problem is worth paying to solve"].map((x,i)=><div key={x} className="flex gap-5 py-5"><span className="text-xs font-semibold text-black/40">0{i+1}</span><span className="text-sm font-semibold uppercase tracking-[0.08em]">{x}</span></div>)}</div><p className="mt-8 text-sm leading-relaxed text-black/55">No school name is requested. Findings will be reported in aggregate.</p></aside></div></section></main>;
 if(done)return <main className="min-h-screen bg-[#f3f0e8] text-black"><header className="border-b border-black/20"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="text-sm font-semibold tracking-[0.18em]">FORGE</Link><span className="text-xs font-semibold tracking-[0.16em] text-black/55">RESEARCH #02 · RECORDED</span></div></header><section><div className="mx-auto grid max-w-[1500px] md:grid-cols-12"><div className="border-b border-black/20 px-6 py-14 md:col-span-8 md:min-h-[75vh] md:border-b-0 md:border-r md:px-10 md:py-20"><p className="text-xs font-semibold tracking-[0.18em] text-black/50">THANK YOU</p><h1 className="mt-8 max-w-4xl text-6xl font-semibold uppercase leading-[0.88] tracking-[-0.06em] md:text-8xl">Evidence before solutions.</h1><p className="mt-10 max-w-2xl text-xl leading-relaxed">Your response is now part of FORGE Research #02. As the dataset grows, FORGE will publish anonymised patterns about where fixture operations create unnecessary workload and where existing systems work well.</p></div><div className="px-6 py-14 md:col-span-4 md:px-10 md:py-20"><p className="text-xs font-semibold tracking-[0.18em] text-black/50">THE QUESTION</p><p className="mt-6 text-3xl font-semibold uppercase leading-tight tracking-[-0.04em]">Is fixture administration a software problem, a process problem, or simply part of running school sport?</p><p className="mt-8 leading-relaxed text-black/60">The evidence will decide.</p><Link href="/" className="mt-10 inline-block bg-black px-6 py-4 text-xs font-semibold tracking-[0.14em] text-white">RETURN TO FORGE</Link></div></div></section></main>;
 return <main className="min-h-screen bg-[#f3f0e8] text-black"><header className="border-b border-black/20"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="text-sm font-semibold tracking-[0.18em]">FORGE</Link><span className="text-xs font-semibold tracking-[0.16em] text-black/55">RESEARCH #02 · {step+1}/7</span></div></header><div className="h-1 bg-black/10"><div className="h-full bg-black transition-all" style={{width:`${((step+1)/7)*100}%`}}/></div><section className="mx-auto grid max-w-[1500px] md:grid-cols-12"><aside className="border-b border-black/20 px-6 py-10 md:col-span-4 md:min-h-[calc(100vh-100px)] md:border-b-0 md:border-r md:px-10 md:py-14"><p className="text-xs font-semibold tracking-[0.18em] text-black/45">SECTION {step+1} OF 7</p><h1 className="mt-5 text-4xl font-semibold uppercase tracking-[-0.05em]">{sections[step]}</h1><p className="mt-6 max-w-sm leading-relaxed text-black/60">{["Help us compare responses without identifying your school.","What actually holds the operation together today?","Identify the work that creates disproportionate effort.","How much human time is being absorbed?","Where does the current system fail under pressure?","Describe the outcome, not the feature.","Interest is useful. Willingness to pay is stronger evidence."][step]}</p></aside><div className="px-6 py-10 md:col-span-8 md:px-10 md:py-14">
 {step===0&&<div className="space-y-10"><Q n="01" t="What best describes your role?"/><div className="grid gap-2 md:grid-cols-2">{roles.map(x=><Option key={x} label={x} selected={a.role===x} onClick={()=>setA(p=>({...p,role:x}))}/>)}</div><Q n="02" t="Roughly how many fixtures or competitions does your department manage in a typical term?"/><div className="grid gap-2 md:grid-cols-2">{volumes.map(x=><Option key={x} label={x} selected={a.fixture_volume===x} onClick={()=>setA(p=>({...p,fixture_volume:x}))}/>)}</div></div>}
 {step===1&&<><Q n="03" t="What do you currently use to manage fixture operations?" sub="Select all that apply."/><div className="grid gap-2 md:grid-cols-2">{tools.map(x=><Option key={x} label={x} selected={a.current_tools.includes(x)} onClick={()=>toggle("current_tools",x)}/>)}</div></>}
 {step===2&&<div className="space-y-10"><div><Q n="04" t="Which THREE parts create the most friction?" sub="Choose up to three."/><div className="grid gap-2 md:grid-cols-2">{frictions.map(x=><Option key={x} label={x} selected={a.top_friction.includes(x)} onClick={()=>toggle("top_friction",x,3)}/>)}</div></div><div className="border-t border-black/20 pt-8"><Q n="05" t="If you could permanently remove ONE of those headaches, which would you choose?"/><textarea value={a.biggest_headache} onChange={e=>setA(p=>({...p,biggest_headache:e.target.value}))} rows={4} maxLength={1500} placeholder="One or two sentences is enough." className="mt-5 w-full border border-black/25 bg-transparent px-4 py-4 outline-none focus:border-black"/></div></div>}
 {step===3&&<><Q n="06" t="In a busy week, roughly how much staff time goes into fixture administration?"/><div className="grid gap-2 md:grid-cols-2">{["Less than 2 hours","2–5 hours","6–10 hours","11–20 hours","20+ hours","Don't know"].map(x=><Option key={x} label={x} selected={a.admin_hours===x} onClick={()=>setA(p=>({...p,admin_hours:x}))}/>)}</div></>}
 {step===4&&<div className="space-y-10"><div><Q n="07" t="Where do things most commonly break down?"/><div className="grid gap-2 md:grid-cols-2">{breakdowns.map(x=><Option key={x} label={x} selected={a.breakdown_point===x} onClick={()=>setA(p=>({...p,breakdown_point:x}))}/>)}</div></div><div className="border-t border-black/20 pt-8"><Q n="08" t="Overall, how satisfied are you with your current fixture workflow?" sub="0 = constant friction · 10 = works extremely well"/><div className="mt-6 grid grid-cols-6 gap-2 md:grid-cols-11">{Array.from({length:11},(_,i)=>i).map(v=><button key={v} onClick={()=>setA(p=>({...p,satisfaction:v}))} className={`min-h-14 border text-lg font-semibold ${a.satisfaction===v?"border-black bg-black text-white":"border-black/25"}`}>{v}</button>)}</div></div></div>}
 {step===5&&<><Q n="09" t="Imagine one lightweight system handled your highest-friction fixture workflow properly. What would you most want it to do?" sub="Use your own words. We don't want to suggest features."/><textarea value={a.desired_outcome} onChange={e=>setA(p=>({...p,desired_outcome:e.target.value}))} rows={6} maxLength={1500} placeholder="What outcome would make a real difference?" className="mt-5 w-full border border-black/25 bg-transparent px-4 py-4 outline-none focus:border-black"/></>}
 {step===6&&<div className="space-y-10"><div><Q n="10" t="If something genuinely saved your department several hours of fixture administration each week, which best describes your reaction?"/><div className="grid gap-2">{intents.map(x=><Option key={x} label={x} selected={a.commercial_intent===x} onClick={()=>setA(p=>({...p,commercial_intent:x}))}/>)}</div></div><div className="border-t border-black/20 pt-8"><label className="text-xs font-semibold tracking-[0.14em] text-black/50">OPTIONAL · WANT THE FINDINGS?</label><input type="email" value={a.email} onChange={e=>setA(p=>({...p,email:e.target.value}))} placeholder="Email address" className="mt-5 w-full border border-black/25 bg-transparent px-4 py-4 outline-none focus:border-black"/><p className="mt-3 text-xs leading-relaxed text-black/45">Optional. No school name is requested. Findings will be reported in aggregate.</p></div></div>}
 <div className="mt-12 flex items-center justify-between border-t border-black/20 pt-8"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0||saving} className="px-2 py-4 text-xs font-semibold tracking-[0.14em] disabled:opacity-25">PREVIOUS</button>{step<6?<button onClick={()=>{if(valid){setStep(s=>s+1);window.scrollTo({top:0,behavior:"smooth"})}}} disabled={!valid} className="bg-black px-7 py-4 text-xs font-semibold tracking-[0.14em] text-white disabled:opacity-25">NEXT</button>:<button onClick={submit} disabled={!valid||saving} className="bg-black px-7 py-4 text-xs font-semibold tracking-[0.14em] text-white disabled:opacity-25">{saving?"SAVING...":"SUBMIT RESEARCH"}</button>}</div>{error&&<p className="mt-4 text-sm text-black/65">{error}</p>}
 </div></section></main>
}
function Q({n,t,sub}:{n:string;t:string;sub?:string}){return <div><p className="text-xs font-semibold text-black/40">{n}</p><h2 className="mt-3 max-w-3xl text-2xl font-semibold leading-snug md:text-3xl">{t}</h2>{sub&&<p className="mt-3 text-sm text-black/50">{sub}</p>}</div>}
