'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';

type Draft={decision:string;outcome:string;options:string;assumptions:string;prediction:string;confidence:string;reviewDate:string};
type PastAssumption={statement:string;status:string};
const empty:Draft={decision:'',outcome:'',options:'',assumptions:'',prediction:'',confidence:'70',reviewDate:''};
const lines=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean);
const words=(v:string)=>new Set(v.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>3));
const isoAfter=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};

export default function NewDecision(){
 const router=useRouter(); const[userId,setUserId]=useState(''); const[d,setD]=useState<Draft>(empty); const[saving,setSaving]=useState(false); const[msg,setMsg]=useState(''); const[stage,setStage]=useState<'draft'|'check'>('draft'); const[past,setPast]=useState<PastAssumption[]>([]);
 useEffect(()=>{void (async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.push('/login');return}setUserId(data.user.id);const{data:assumptions}=await supabase.from('decision_assumptions').select('statement,status').limit(200);setPast((assumptions||[]) as PastAssumption[])})()},[router]);
 const warning=useMemo(()=>{const current=lines(d.assumptions);if(!current.length)return null;let best:{current:string;past:string;score:number}|null=null;for(const c of current){const cw=words(c);for(const p of past.filter(x=>x.status==='invalidated')){const pw=words(p.statement);const overlap=[...cw].filter(w=>pw.has(w)).length;if(overlap>0&&(!best||overlap>best.score))best={current:c,past:p.statement,score:overlap}}}return best},[d.assumptions,past]);
 function check(e:FormEvent){e.preventDefault();if(!d.decision.trim())return;if(!d.reviewDate)setD(v=>({...v,reviewDate:isoAfter(90)}));setStage('check');window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){if(!userId||!d.decision.trim())return;setSaving(true);setMsg('');const confidence=Math.max(0,Math.min(100,Number(d.confidence)||0));const reviewDate=d.reviewDate||isoAfter(90);
  const{data,error}=await supabase.from('decision_intakes').insert({user_id:userId,title:d.decision.trim().slice(0,100),decision:d.decision.trim(),context:'Captured through simplified Forge flow',constraints:'None recorded',options:lines(d.options),difficulty:'meaningful',status:'SUBMITTED',desired_outcome:d.outcome.trim()||null,confidence,expected_result:d.prediction.trim()||null,review_date:reviewDate,decided_at:new Date().toISOString()}).select('id').single();
  if(error||!data){setMsg(error?.message||'Could not save decision.');setSaving(false);return}
  const assumptions=lines(d.assumptions).map(statement=>({user_id:userId,decision_id:data.id,statement,confidence}));const predictions=d.prediction.trim()?[{user_id:userId,decision_id:data.id,prediction:d.prediction.trim(),probability:confidence,target_date:reviewDate}]:[];
  const[a,p]=await Promise.all([assumptions.length?supabase.from('decision_assumptions').insert(assumptions):Promise.resolve({error:null}),predictions.length?supabase.from('decision_predictions').insert(predictions):Promise.resolve({error:null})]);
  if(a.error||p.error){setMsg('Decision saved, but one linked item needs attention.');setSaving(false);return}router.push('/your-forge');
 }
 if(stage==='check')return <main className="min-h-screen bg-forge-ivory-50 text-forge-charcoal-900"><Nav/><section className="mx-auto max-w-3xl px-5 py-10 md:px-8 md:py-14"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-600">Forge check</p><h1 className="mt-3 font-serif text-4xl text-forge-forest-950 md:text-5xl">Before you commit.</h1><p className="mt-4 text-lg text-forge-stone-600">A quick check of the thinking behind your decision.</p>{msg&&<div className="mt-6 border border-forge-bronze-300 bg-white p-4 text-sm">{msg}</div>}
 <div className="mt-8 space-y-5"><Card label="Your decision"><p className="font-serif text-2xl text-forge-forest-950">{d.decision}</p>{d.outcome&&<p className="mt-3 text-sm text-forge-stone-600"><strong>Success looks like:</strong> {d.outcome}</p>}</Card><Card label="You are assuming">{lines(d.assumptions).length?<ul className="space-y-2 text-sm">{lines(d.assumptions).map((a,i)=><li key={i}>• {a}</li>)}</ul>:<p className="text-sm text-forge-stone-500">No assumptions recorded.</p>}</Card><Card label="You expect"><p className="text-sm">{d.prediction||'No testable expectation recorded.'}</p><p className="mt-3 font-serif text-3xl text-forge-forest-950">{d.confidence}% <span className="font-sans text-xs uppercase tracking-forge text-forge-stone-500">confidence</span></p></Card>
 {warning&&<div className="border border-forge-bronze-400 bg-forge-bronze-50 p-5"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-700">Your history</p><p className="mt-2 font-semibold">Check this assumption carefully.</p><p className="mt-2 text-sm leading-6 text-forge-stone-700">A similar belief in your history was later invalidated: “{warning.past}”</p></div>}
 <div className="border border-forge-forest-800 bg-forge-forest-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-300">One last challenge</p><p className="mt-3 font-serif text-2xl">What would make this decision fail?</p><p className="mt-3 text-sm leading-6 text-white/70">Look at your assumptions. If the weakest one turns out to be wrong, would you still make the same decision?</p></div>
 <div className="flex flex-col gap-3 sm:flex-row"><button onClick={()=>setStage('draft')} className="flex-1 border border-forge-forest-900 px-5 py-4 font-semibold text-forge-forest-950">Change my thinking</button><button onClick={save} disabled={saving} className="flex-1 bg-forge-forest-950 px-5 py-4 font-semibold text-white disabled:opacity-50">{saving?'Committing…':'Commit decision'}</button></div><p className="text-center text-xs text-forge-stone-500">Forge will bring this back on {d.reviewDate||isoAfter(90)} so you can compare what you believed with what actually happened.</p></div></section></main>;
 return <main className="min-h-screen bg-forge-ivory-50 text-forge-charcoal-900"><Nav/><section className="mx-auto max-w-3xl px-5 py-10 md:px-8 md:py-14"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-600">Think better now. Learn later.</p><h1 className="mt-3 font-serif text-4xl text-forge-forest-950 md:text-5xl">What are you deciding?</h1><p className="mt-4 text-lg text-forge-stone-600">Two minutes now gives Forge something real to learn from later.</p>
 <form onSubmit={check} className="mt-8 space-y-6 border border-forge-ivory-200 bg-white p-6 md:p-8"><Field n="1" label="What are you deciding?"><textarea required className="input min-h-24" value={d.decision} onChange={e=>setD({...d,decision:e.target.value})} placeholder="e.g. Should we launch the pilot in October?"/></Field><Field n="2" label="What outcome do you want?"><textarea className="input min-h-20" value={d.outcome} onChange={e=>setD({...d,outcome:e.target.value})} placeholder="What would success look like?"/></Field><Field n="3" label="What are your main options?"><textarea className="input min-h-20" value={d.options} onChange={e=>setD({...d,options:e.target.value})} placeholder={'One option per line\nLaunch now\nDelay one month'}/></Field><Field n="4" label="What needs to be true for this to work?"><textarea className="input min-h-24" value={d.assumptions} onChange={e=>setD({...d,assumptions:e.target.value})} placeholder={'One belief per line\ne.g. Staff will have enough capacity\nDemand will remain strong'}/></Field><Field n="5" label="What do you expect to happen?"><textarea className="input min-h-20" value={d.prediction} onChange={e=>setD({...d,prediction:e.target.value})} placeholder="Be specific enough that Forge can check later."/></Field><div className="grid gap-5 sm:grid-cols-2"><Field n="6" label="How confident are you?"><div className="flex items-center gap-4"><input type="range" min="0" max="100" step="5" value={d.confidence} onChange={e=>setD({...d,confidence:e.target.value})} className="w-full"/><span className="w-14 text-right font-serif text-2xl">{d.confidence}%</span></div></Field><Field n="7" label="When should Forge check back?"><div className="grid grid-cols-3 gap-2"><button type="button" onClick={()=>setD({...d,reviewDate:isoAfter(30)})} className="border border-forge-ivory-300 px-2 py-2 text-xs">30 days</button><button type="button" onClick={()=>setD({...d,reviewDate:isoAfter(90)})} className="border border-forge-ivory-300 px-2 py-2 text-xs">90 days</button><button type="button" onClick={()=>setD({...d,reviewDate:isoAfter(180)})} className="border border-forge-ivory-300 px-2 py-2 text-xs">6 months</button></div><input type="date" className="input mt-2" value={d.reviewDate} onChange={e=>setD({...d,reviewDate:e.target.value})}/></Field></div><div className="border-t border-forge-ivory-200 pt-6"><button className="w-full bg-forge-forest-950 px-5 py-4 font-semibold text-white">Check my decision</button><p className="mt-3 text-center text-xs text-forge-stone-500">Nothing is committed yet. Forge will challenge the thinking first.</p></div></form></section></main>
}
function Card({label,children}:{label:string;children:React.ReactNode}){return <div className="border border-forge-ivory-200 bg-white p-5"><p className="mb-3 text-xs font-semibold uppercase tracking-forge text-forge-bronze-600">{label}</p>{children}</div>}
function Field({n,label,children}:{n:string;label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-sm font-semibold"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-forge-ivory-100 text-xs">{n}</span>{label}</span>{children}</label>}
function Nav(){return <header className="border-b border-forge-ivory-200 bg-forge-forest-950 text-white"><div className="mx-auto flex max-w-forge items-center justify-between px-5 py-5 md:px-8"><a href="/your-forge" className="font-serif text-2xl">FORGE</a><nav className="flex gap-5 text-sm"><a href="/new-decision" className="font-semibold text-forge-bronze-300">New decision</a><a href="/reviews">Reviews</a><a href="/your-forge">Your Forge</a></nav></div></header>}
