'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';

type Decision={id:string;title:string;decision:string;context:string;domain:string|null;decision_type:string|null;desired_outcome:string|null;supporting_evidence:string|null;confidence:number|null;created_at:string};
type Assumption={id:string;decision_id:string;statement:string;status:string;confidence:number|null;category:string|null;invalidated_at:string|null};
type Prediction={id:string;decision_id:string;prediction:string;probability:number|null;resolution_status:string;resolved_result:boolean|null;resolved_text:string|null;brier_score:number|null};
type Review={id:string;decision_id:string;lesson:string|null;future_rule:string|null;process_quality_score:number|null;outcome_quality_score:number|null;reviewed_at:string};

type MemoryResult={decision:Decision;score:number;failedAssumptions:Assumption[];resolvedPredictions:Prediction[];rules:string[];lessons:string[]};

const stop=new Set(['the','and','for','that','with','this','from','into','have','will','your','what','when','where','which','about','should','could','would','are','was','were','been','being','our','their','them','they','you','not','but','can','how','why','who','too','very','more','most','some','any','all']);
function tokens(v:string){return Array.from(new Set(v.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x))))}
function overlap(a:string[],b:string[]){if(!a.length||!b.length)return 0;const bs=new Set(b);return a.filter(x=>bs.has(x)).length/Math.max(3,Math.min(a.length,b.length))}
function pct(n:number|null){return typeof n==='number'?`${n}%`:'—'}

export default function DecisionMemoryPage(){
 const router=useRouter();const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[query,setQuery]=useState('');const[domain,setDomain]=useState('');const[type,setType]=useState('');const[decisions,setDecisions]=useState<Decision[]>([]);const[assumptions,setAssumptions]=useState<Assumption[]>([]);const[predictions,setPredictions]=useState<Prediction[]>([]);const[reviews,setReviews]=useState<Review[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){const{data:u,error}=await supabase.auth.getUser();if(error||!u.user){router.push('/login');return}const[d,a,p,r]=await Promise.all([
  supabase.from('decision_intakes').select('id,title,decision,context,domain,decision_type,desired_outcome,supporting_evidence,confidence,created_at').order('created_at',{ascending:false}),
  supabase.from('decision_assumptions').select('id,decision_id,statement,status,confidence,category,invalidated_at'),
  supabase.from('decision_predictions').select('id,decision_id,prediction,probability,resolution_status,resolved_result,resolved_text,brier_score'),
  supabase.from('decision_reviews').select('id,decision_id,lesson,future_rule,process_quality_score,outcome_quality_score,reviewed_at').order('reviewed_at',{ascending:false})
 ]);const err=d.error||a.error||p.error||r.error;if(err)setMessage(err.message);setDecisions((d.data||[]) as Decision[]);setAssumptions((a.data||[]) as Assumption[]);setPredictions((p.data||[]) as Prediction[]);setReviews((r.data||[]) as Review[]);setLoading(false)}
 const results=useMemo(()=>{const q=tokens(query);if(q.length<1&&!domain&&!type)return [] as MemoryResult[];return decisions.map(d=>{const corpus=tokens([d.title,d.decision,d.context,d.desired_outcome||'',d.supporting_evidence||''].join(' '));let score=overlap(q,corpus)*70;if(domain&&d.domain===domain)score+=20;if(type&&d.decision_type===type)score+=10;const failed=assumptions.filter(a=>a.decision_id===d.id&&(a.status==='invalidated'||Boolean(a.invalidated_at)));const resolved=predictions.filter(p=>p.decision_id===d.id&&p.resolution_status==='resolved');const rs=reviews.filter(r=>r.decision_id===d.id);if(failed.length)score+=Math.min(8,failed.length*2);if(rs.some(r=>r.future_rule))score+=4;return{decision:d,score,failedAssumptions:failed,resolvedPredictions:resolved,rules:rs.map(r=>r.future_rule).filter((x):x is string=>Boolean(x)),lessons:rs.map(r=>r.lesson).filter((x):x is string=>Boolean(x))}}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score).slice(0,6)},[query,domain,type,decisions,assumptions,predictions,reviews]);
 const warnings=useMemo(()=>{const out:string[]=[];for(const r of results.slice(0,3)){for(const a of r.failedAssumptions.slice(0,2))out.push(`Past failed assumption: “${a.statement}” (${r.decision.title})`);for(const rule of r.rules.slice(0,1))out.push(`Carry-forward rule: ${rule}`)}return Array.from(new Set(out)).slice(0,6)},[results]);
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-forge-ivory-50"><p>Loading decision memory...</p></main>;
 return <main className="min-h-screen bg-forge-ivory-50 text-forge-charcoal-900">
  <header className="border-b border-forge-ivory-200 bg-forge-forest-950 text-white"><div className="mx-auto flex max-w-forge items-center justify-between px-5 py-5 md:px-8"><div><a href="/" className="font-serif text-2xl">FORGE</a><p className="mt-1 text-xs uppercase tracking-forge text-forge-bronze-300">Decision memory</p></div><div className="flex gap-5 text-sm"><a href="/decision-ledger" className="underline underline-offset-4">Ledger</a><a href="/assumption-intelligence" className="underline underline-offset-4">Assumptions</a><a href="/calibration" className="underline underline-offset-4">Calibration</a></div></div></header>
  <section className="mx-auto max-w-forge px-5 py-10 md:px-8 md:py-14">
   <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-600">Before you decide</p><h1 className="mt-3 font-serif text-4xl text-forge-forest-950 md:text-5xl">Ask your own history first.</h1><p className="mt-4 leading-7 text-forge-stone-600">Describe the decision you are considering. Forge retrieves the closest prior decisions, failed assumptions, resolved forecasts and rules you previously said should guide future judgement.</p></div>
   {message&&<div className="mt-6 border border-forge-bronze-300 bg-white p-4 text-sm">{message}</div>}
   <section className="mt-8 border border-forge-ivory-200 bg-white p-6 md:p-8"><div className="grid gap-4 lg:grid-cols-[1fr_180px_180px]"><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Should we add another coach to improve programme quality and reduce workload?" className="min-h-28 border border-forge-ivory-300 bg-forge-ivory-50 px-4 py-3 text-sm outline-none focus:border-forge-forest-800"/><select value={domain} onChange={e=>setDomain(e.target.value)} className="border border-forge-ivory-300 bg-forge-ivory-50 px-3 py-3 text-sm"><option value="">Any domain</option><option value="sport">Sport</option><option value="forge">Forge</option><option value="leadership">Leadership</option><option value="capital">Capital</option><option value="personal">Personal</option></select><select value={type} onChange={e=>setType(e.target.value)} className="border border-forge-ivory-300 bg-forge-ivory-50 px-3 py-3 text-sm"><option value="">Any type</option><option value="operational">Operational</option><option value="people">People</option><option value="strategic">Strategic</option><option value="investment">Investment</option><option value="selection">Selection</option><option value="risk">Risk</option></select></div></section>
   {warnings.length>0&&<section className="mt-8 border border-forge-forest-800 bg-forge-forest-950 p-6 text-white md:p-8"><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-300">Memory warnings</p><h2 className="mt-2 font-serif text-3xl">What your history says to check</h2><div className="mt-5 space-y-3">{warnings.map(w=><p key={w} className="border-t border-white/15 pt-3 text-sm leading-6 first:border-t-0 first:pt-0">{w}</p>)}</div></section>}
   <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-forge text-forge-bronze-600">Retrieved memory</p><h2 className="mt-2 font-serif text-3xl text-forge-forest-950">Relevant prior decisions</h2></div><p className="text-xs text-forge-stone-500">Deterministic retrieval v0</p></div><div className="mt-6 space-y-5">{results.length?results.map((r,i)=><article key={r.decision.id} className="border border-forge-ivory-200 bg-white p-6 md:p-7"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div><p className="text-xs uppercase tracking-forge text-forge-stone-500">#{i+1} · {r.decision.domain||'general'} · {r.decision.decision_type||'decision'}</p><h3 className="mt-2 font-serif text-2xl text-forge-forest-950">{r.decision.title}</h3><p className="mt-3 text-sm leading-6 text-forge-stone-700">{r.decision.decision}</p></div><div className="shrink-0 md:text-right"><p className="text-xs uppercase tracking-forge text-forge-stone-500">Original confidence</p><p className="mt-1 font-serif text-3xl">{pct(r.decision.confidence)}</p></div></div>
    {r.failedAssumptions.length>0&&<div className="mt-5 border-t border-forge-ivory-200 pt-4"><p className="text-xs font-semibold uppercase tracking-forge text-forge-stone-500">Failed assumptions</p>{r.failedAssumptions.slice(0,3).map(a=><p key={a.id} className="mt-2 text-sm">• {a.statement}</p>)}</div>}
    {r.resolvedPredictions.length>0&&<div className="mt-5 border-t border-forge-ivory-200 pt-4"><p className="text-xs font-semibold uppercase tracking-forge text-forge-stone-500">Resolved forecasts</p>{r.resolvedPredictions.slice(0,3).map(p=><p key={p.id} className="mt-2 text-sm">• {p.prediction} · {p.probability??'—'}% · {p.resolved_result?'occurred':'did not occur'}{typeof p.brier_score==='number'?` · Brier ${p.brier_score.toFixed(3)}`:''}</p>)}</div>}
    {(r.lessons.length>0||r.rules.length>0)&&<div className="mt-5 grid gap-4 border-t border-forge-ivory-200 pt-4 md:grid-cols-2">{r.lessons.length>0&&<div><p className="text-xs font-semibold uppercase tracking-forge text-forge-stone-500">Lesson</p><p className="mt-2 text-sm leading-6">{r.lessons[0]}</p></div>}{r.rules.length>0&&<div><p className="text-xs font-semibold uppercase tracking-forge text-forge-stone-500">Future rule</p><p className="mt-2 text-sm leading-6 font-semibold">{r.rules[0]}</p></div>}</div>}
   </article>):<div className="border border-forge-ivory-200 bg-white p-8 text-sm text-forge-stone-500">Describe a decision above to search your history. Retrieval gets more useful as Forge accumulates resolved decisions.</div>}</div></section>
  </section>
 </main>
}
