import Link from "next/link";

const ForgeMark = ({ className = "" }: { className?: string }) => <img src="/forge-mark.png" alt="" className={className} aria-hidden="true" />;

const products = [
  ["01", "Systems Stress Test", "Assess leadership, ownership, operations, knowledge continuity and capacity to improve.", "/stress-test", "Take the Stress Test"],
  ["02", "Readiness Check", "Find unresolved operational gaps that could disrupt the start of a year or season.", "/readiness-check", "Check readiness"],
  ["03", "Department Benchmarking", "A developing evidence base for confidential comparison with relevant peers.", "/benchmarking", "Explore benchmarking"],
];

export default function DepartmentsPage() {
  return (
    <main className="forge-light overflow-hidden">
      <header className="border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Forge home"><ForgeMark className="h-9 w-9" /><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><nav className="hidden items-center gap-8 text-[11px] font-semibold uppercase tracking-[0.14em] lg:flex"><Link href="/departments" className="text-[var(--forge-bronze)]">Departments</Link><Link href="/associations">Associations</Link><Link href="/benchmarking">Benchmarking</Link><Link href="/about">About</Link></nav><Link href="/diagnostics" className="forge-button forge-button-primary">Diagnostics</Link></div></header>

      <section className="forge-dark border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid min-h-[700px] gap-14 py-20 lg:grid-cols-12 lg:items-end lg:py-28"><div className="lg:col-span-4 lg:self-start"><p className="forge-eyebrow">Forge for departments</p></div><div className="lg:col-span-8"><h1 className="forge-display max-w-5xl text-[clamp(4rem,7.2vw,7.8rem)]">Understand how your sports operation works.</h1><p className="mt-10 max-w-3xl text-xl leading-9 text-[rgba(246,244,238,0.7)]">Forge provides practical diagnostics and research for Directors of Sport, Athletic Directors and other school sports leaders.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/stress-test" className="forge-button forge-button-primary">Take the Stress Test</Link><Link href="/readiness-check" className="forge-button">Check readiness</Link></div></div></div></section>

      <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Department research</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Look beyond the calendar.</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-[rgba(17,19,17,0.66)]">A sports programme depends on clear roles, repeatable processes, accessible information, manageable workload and continuity when people change.</p></div></div><div className="mt-16 grid border-l border-t forge-border lg:grid-cols-3">{products.map(([number,title,text,href,cta]) => <article key={number} className="flex min-h-[340px] flex-col justify-between border-b border-r p-8 forge-border"><div><span className="forge-eyebrow">{number}</span><h3 className="forge-heading mt-12 text-4xl text-[var(--forge-forest-deep)]">{title}</h3><p className="mt-6 text-sm leading-7 text-[rgba(17,19,17,0.62)]">{text}</p></div><Link href={href} className="mt-10 w-fit text-xs font-semibold uppercase tracking-[0.13em] text-[var(--forge-bronze)] underline underline-offset-8">{cta}</Link></article>)}</div></section>

      <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Research over time</p></div><div className="lg:col-span-8"><h2 className="forge-heading max-w-4xl text-5xl md:text-7xl">Build a better evidence base.</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-[rgba(246,244,238,0.7)]">Aggregated diagnostic data can help identify recurring patterns across school sport. Any benchmark comparison will only be presented when the underlying data is sufficiently consistent and comparable.</p><Link href="/benchmarking" className="mt-10 inline-block text-xs font-semibold uppercase tracking-[0.14em] text-[var(--forge-bronze)] underline underline-offset-8">Explore benchmarking</Link></div></div></section>

      <section className="forge-section"><div className="forge-container grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Start here</p><h2 className="forge-heading mt-8 max-w-4xl text-5xl text-[var(--forge-forest-deep)] md:text-7xl">Choose the diagnostic that matches your current need.</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/diagnostics" className="forge-button forge-button-primary">View diagnostics</Link></div></div></section>
    </main>
  );
}
