import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Dependency Audit | Forge Systems", description: "A lightweight Forge research protocol for finding where a school sports operation depends too heavily on individual people." };

export default function DependencyAuditPage() {
  const steps = [
    ["01", "Capture", "For five working days, log each moment where delivery requires one specific person to remember, approve, explain, decide or rescue something."],
    ["02", "Classify", "Tag each item as decision right, unclear ownership, missing information, undocumented process or relationship knowledge."],
    ["03", "Count", "Look for repeated dependencies. Frequency matters more than how irritating one incident felt."],
    ["04", "Remove", "Choose one repeated dependency and change the system: assign ownership, document the critical information, define the decision rule or redesign the workflow."],
    ["05", "Retest", "Two weeks later, check whether the issue can now be handled without the previously essential person."],
  ];

  return <main className="forge-light overflow-hidden">
    <header className="border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><img src="/forge-mark.png" alt="" className="h-9 w-9" aria-hidden="true"/><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><Link href="/systems" className="text-[11px] font-semibold uppercase tracking-[0.14em]">Research tools</Link></div></header>
    <section className="border-b forge-border"><div className="forge-container grid gap-12 py-20 lg:grid-cols-12 lg:py-28"><div className="lg:col-span-4"><p className="forge-eyebrow">Research tool 001</p></div><div className="lg:col-span-8"><h1 className="forge-display max-w-5xl text-[clamp(4rem,7vw,7rem)] text-[var(--forge-forest-deep)]">Dependency Audit.</h1><p className="mt-9 max-w-3xl text-xl leading-9 text-[rgba(17,19,17,0.68)]">A five-day protocol for finding the places where your sports operation relies on a person when it should rely on a system.</p></div></div></section>
    <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Use this when</p></div><div className="lg:col-span-8 grid gap-px bg-[rgba(17,19,17,0.14)] md:grid-cols-2">{["You are repeatedly interrupted to solve routine issues.","A colleague's absence exposes gaps nobody noticed before.","Important information lives in messages, memory or personal spreadsheets.","You are worried the operation would struggle through a leadership transition."].map((x,i)=><div key={x} className="bg-[var(--forge-cream)] p-8"><span className="forge-eyebrow">0{i+1}</span><p className="forge-heading mt-7 text-2xl text-[var(--forge-forest-deep)]">{x}</p></div>)}</div></div></section>
    <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container"><div className="mb-12 grid gap-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Protocol</p></div><div className="lg:col-span-8"><h2 className="forge-heading text-5xl md:text-7xl">Find the dependency. Remove one cause.</h2></div></div><div className="border-t border-[rgba(185,134,74,0.35)]">{steps.map(([n,t,x])=><div key={n} className="grid gap-5 border-b border-[rgba(185,134,74,0.35)] py-8 md:grid-cols-[90px_1fr_2fr]"><span className="forge-eyebrow">{n}</span><h3 className="forge-heading text-2xl">{t}</h3><p className="text-sm leading-7 text-[rgba(246,244,238,0.7)]">{x}</p></div>)}</div></div></section>
    <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Working log</p></div><div className="lg:col-span-8"><div className="overflow-x-auto border forge-border"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b forge-border"><tr>{["Incident","Person required","Why required","Category","System change"].map(x=><th key={x} className="p-4 text-[10px] uppercase tracking-[0.12em]">{x}</th>)}</tr></thead><tbody>{[1,2,3,4].map(i=><tr key={i} className="border-b forge-border last:border-0">{[1,2,3,4,5].map(j=><td key={j} className="h-14 border-r forge-border p-4 last:border-r-0">&nbsp;</td>)}</tr>)}</tbody></table></div><p className="mt-6 text-sm leading-7 text-[rgba(17,19,17,0.56)]">Keep the exercise deliberately small. The goal is not to document the whole operation. It is to expose one recurring dependency worth removing.</p></div></div></section>
    <section className="forge-dark forge-section"><div className="forge-container grid gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">Contribute to the wider research</p><h2 className="forge-heading mt-7 text-5xl md:text-7xl">See the wider operating profile.</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/stress-test" className="forge-button forge-button-primary">Take the stress test</Link></div></div></section>
  </main>;
}
