import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Coaching Baseline | Forge Systems", description: "A practical Forge protocol for defining and checking minimum coaching standards across a school sport department." };

export default function CoachingBaselinePage() {
  const steps = [
    ["01", "Define", "Agree five observable coaching behaviours that should be true across every sport and team."],
    ["02", "Describe", "For each behaviour, write what strong practice looks like in concrete language rather than slogans."],
    ["03", "Induct", "Use the baseline in coach induction so expectations are explicit before delivery begins."],
    ["04", "Observe", "Sample practice through short observations, athlete voice or review conversations. Look for patterns, not isolated mistakes."],
    ["05", "Coach", "Use the same baseline for feedback and development so improvement conversations are anchored to shared standards."],
  ];

  return <main className="forge-light overflow-hidden">
    <header className="border-b forge-border"><div className="forge-container flex h-[76px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><img src="/forge-mark.png" alt="" className="h-9 w-9" aria-hidden="true"/><span className="text-sm font-semibold tracking-[0.2em]">FORGE</span></Link><Link href="/systems" className="text-[11px] font-semibold uppercase tracking-[0.14em]">All systems</Link></div></header>
    <section className="border-b forge-border"><div className="forge-container grid gap-12 py-20 lg:grid-cols-12 lg:py-28"><div className="lg:col-span-4"><p className="forge-eyebrow">Forge system 002 / Free protocol</p></div><div className="lg:col-span-8"><h1 className="forge-display max-w-5xl text-[clamp(4rem,7vw,7rem)] text-[var(--forge-forest-deep)]">Coaching Baseline.</h1><p className="mt-9 max-w-3xl text-xl leading-9 text-[rgba(17,19,17,0.68)]">A simple protocol for making minimum coaching standards visible, observable and coachable across different sports.</p></div></div></section>
    <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Use this when</p></div><div className="lg:col-span-8 grid gap-px bg-[rgba(17,19,17,0.14)] md:grid-cols-2">{["Different teams offer noticeably different athlete experiences.","You are relying on individual coaches to interpret what good coaching means.","Parent or athlete concerns appear before internal review catches the issue.","Coach induction explains logistics better than professional expectations."].map((x,i)=><div key={x} className="bg-[var(--forge-cream)] p-8"><span className="forge-eyebrow">0{i+1}</span><p className="forge-heading mt-7 text-2xl text-[var(--forge-forest-deep)]">{x}</p></div>)}</div></div></section>
    <section className="forge-forest forge-section border-b border-[rgba(185,134,74,0.35)]"><div className="forge-container"><div className="mb-12 grid gap-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Protocol</p></div><div className="lg:col-span-8"><h2 className="forge-heading text-5xl md:text-7xl">Make the standard explicit. Then use it.</h2></div></div><div className="border-t border-[rgba(185,134,74,0.35)]">{steps.map(([n,t,x])=><div key={n} className="grid gap-5 border-b border-[rgba(185,134,74,0.35)] py-8 md:grid-cols-[90px_1fr_2fr]"><span className="forge-eyebrow">{n}</span><h3 className="forge-heading text-2xl">{t}</h3><p className="text-sm leading-7 text-[rgba(246,244,238,0.7)]">{x}</p></div>)}</div></div></section>
    <section className="forge-section border-b forge-border"><div className="forge-container grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="forge-eyebrow">Baseline canvas</p></div><div className="lg:col-span-8"><div className="overflow-x-auto border forge-border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b forge-border"><tr>{["Non-negotiable","What good looks like","How we will observe it","Who owns feedback","Review date"].map(x=><th key={x} className="p-4 text-[10px] uppercase tracking-[0.12em]">{x}</th>)}</tr></thead><tbody>{[1,2,3,4,5].map(i=><tr key={i} className="border-b forge-border last:border-0">{[1,2,3,4,5].map(j=><td key={j} className="h-14 border-r forge-border p-4 last:border-r-0">&nbsp;</td>)}</tr>)}</tbody></table></div><p className="mt-6 text-sm leading-7 text-[rgba(17,19,17,0.56)]">Keep the baseline short. If a coach cannot remember the standards or a leader cannot observe them, they are too abstract.</p></div></div></section>
    <section className="forge-dark forge-section"><div className="forge-container grid gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="forge-eyebrow">See the wider picture</p><h2 className="forge-heading mt-7 text-5xl md:text-7xl">How consistent is the department around the coaching system?</h2></div><div className="lg:col-span-4 lg:text-right"><Link href="/stress-test" className="forge-button forge-button-primary">Take the stress test ↗</Link></div></div></section>
  </main>;
}
